### PR TITLE
feat(mlx): pt.random support with mlx backend

### PR DESCRIPTION
**Pull request by williambdean**
## Description

Basic support for `mlx` random generation.

```python
import pytensor.tensor as pt

data = pt.random.normal(size=(52, 3))

# Works now
data.eval(mode="MLX")
```

They have limited support. Missing Gamma distribution. Could support additional ones
with basic transformations. i.e. `pt.abs(pt.random.normal(...))` ~ Half Normal

MLX Reference: https://ml-explore.github.io/mlx/build/html/python/random.html 

## Related Issue

- [ ] Closes #
- [ ] Related to #

## Checklist

- [ ] Checked that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html)
- [ ] Included tests that prove the fix is effective or that the new feature works
- [ ] Added necessary documentation (docstrings and/or example notebooks)
- [ ] If you are a pro: each commit corresponds to a [relevant logical change](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes)

## Type of change

- [ ] New feature / enhancement
- [ ] Bug fix
- [ ] Documentation
- [ ] Maintenance
- [ ] Other (please specify):

### CODE REVIEW

File: pytensor/link/mlx/linker.py [hunk 1]
```diff
@@ -69,9 +69,16 @@ def create_thunk_inputs(self, storage_map):
...
             The inputs for the thunk
         """
+        from numpy.random import Generator
+
+        from pytensor.link.mlx.dispatch import mlx_typify
+
         thunk_inputs = []
         for n in self.fgraph.inputs:
             sinput = storage_map[n]
+            if isinstance(sinput[0], Generator):
```
Comment (ricardoV94) [inline pytensor/link/mlx/linker.py:138]: you need to do the same dance jax linker does with shared Generator variables

**Review by ricardoV94 — COMMENTED** [review]
missing rng outputs /updates (so consecutive calls get updated rng)

There should be tests in numba/jax you can use as template. Jax is going to be more similar

File: pytensor/link/mlx/dispatch/random.py [hunk 2]
```diff
@@ -0,0 +1,188 @@
...
+import mlx.core as mx
+from numpy.random import Generator
+
+import pytensor.tensor.random.basic as ptr
+from pytensor.link.mlx.dispatch.basic import mlx_funcify, mlx_typify
+from pytensor.link.mlx.dispatch.core import convert_dtype_to_mlx, mlx_to_list_shape
+
+
+def _truncate_pcg64_state_to_uint64(rng: Generator) -> int:
+    return int(rng.bit_generator.state["state"]["state"]) & 0xFFFFFFFFFFFFFFFF
```
Comment (ricardoV94) [inline pytensor/link/mlx/dispatch/random.py]: Shouldn't we combine all 128 bits instead of simply truncating?

Comment (williambdean) [reply pytensor/link/mlx/dispatch/random.py]: MLX only supports 64-bit seeds. 

```python
import mlx.core as mx

for seed in [2**64 - 1, 2**64, 2**65]: 
    try: 
        mx.random.key(seed)
    except Exception as e:
        print(e)
```
would you recommend another another approach?

Comment (ricardoV94) [reply pytensor/link/mlx/dispatch/random.py]: JAX also only, but I think we XOR both sides? Check what it does.

Comment (williambdean) [reply pytensor/link/mlx/dispatch/random.py]: Jax does this :

https://github.com/pymc-devs/pytensor/blob/d6022685ea3bcadcd9a80422a31979b8d6418084/pytensor/link/jax/dispatch/random.py?plain=1#L58-L80

Maybe a bit more complicated. I can use that instead...

Comment (ricardoV94) [reply pytensor/link/mlx/dispatch/random.py]: The main point was just the OR-ing of the two parts of the seed.  I have no idea if it has any better entropy properties than just truncation. Maybe there are principled ways out there we could use instead of going on on vibes

**Comment by jessegrabowski** [comment]
#2010 caused conflicts for this PR. You will need to rebase.

File: pytensor/link/mlx/dispatch/random.py (hunk 2 above)
Comment (williambdean) [reply pytensor/link/mlx/dispatch/random.py]: Alright. Well I just went with a simliar approach to jax. it can be altered or consolidated in the future.

Comment (williambdean) [reply pytensor/link/mlx/dispatch/random.py]: Alright. Well I just went with a simliar approach to jax. it can be altered or consolidated in the future

File: pytensor/link/mlx/dispatch/random.py [hunk 3]
```diff
@@ -0,0 +1,191 @@
...
+
+    return sample_fn
+
+
+@mlx_sample_fn.register(ptr.BernoulliRV)
+def mlx_sample_fn_bernoulli(op, node):
+    def sample_fn(rng_key, size, dtype, p):
+        p = mx.array(p)
+        if size is None:
+            shape = p.shape
```
Comment (ricardoV94) [inline pytensor/link/mlx/dispatch/random.py]: you always need the shape? You didn't need it in the categorical. I would assume you only need when one of the parameters doesn't go in the random function. If so that would take a lot of boilerplate away from your dispatches

File: pytensor/link/mlx/dispatch/random.py [hunk 4]
```diff
@@ -0,0 +1,191 @@
...
+def mlx_sample_fn_categorical(op, node):
+    def sample_fn(rng_key, size, dtype, p):
+        logits = mx.log(mx.array(p))
+        shape = mlx_to_list_shape(size) if size is not None else None
+        return mx.random.categorical(logits=logits, axis=-1, shape=shape, key=rng_key)
+
+    return sample_fn
+
+
+@mlx_sample_fn.register(ptr.MvNormalRV)
```
Comment (ricardoV94) [inline pytensor/link/mlx/dispatch/random.py:139]: MvNormal supports different decomposition strategies, you may want to implement like numba dispatch/op.perform which is more low level if mx.random.multivariate_normal doesn't support them. Or if it's unfeasible issue a warning that it isn't respected and will fallback to svd (if it wasn't svd to begin with)

File: pytensor/link/mlx/dispatch/random.py [hunk 5]
```diff
@@ -0,0 +1,191 @@
...
+
+@mlx_sample_fn.register(ptr.PermutationRV)
+def mlx_sample_fn_permutation(op, node):
+    batch_ndim = op.batch_ndim(node)
+
+    def sample_fn(rng_key, size, dtype, x):
+        if batch_ndim:
+            raise NotImplementedError(
+                "MLX random.permutation does not support batch dimensions."
+            )
```
Comment (ricardoV94) [inline pytensor/link/mlx/dispatch/random.py]: raise at dispatch time already

File: pytensor/link/mlx/dispatch/random.py (hunk 3 above)
Comment (ricardoV94) [reply pytensor/link/mlx/dispatch/random.py]: my comment wasn't about Bernoulli specifically, I would expect you don't need to define shape explicitly (when the user didn't do it themselves) most of the time

**Comment by jessegrabowski** [comment]
why?

**Comment by williambdean** [comment]
Accident

**Comment by jessegrabowski** [comment]
@williambdean what enticements are required to have you get this over the line? It seems to be the last major blocker to mlx-only workflows in pymc

**Comment by williambdean** [comment]
I will take look tonight and tomororw

**Comment by williambdean** [comment]
Changes since last review:

- Simplified Normal shape boilerplate by delegating to `mx.random.normal(loc, scale)` when `size` is None
- Added LogNormal, HalfNormal, Exponential, Logistic, Cauchy dispatches via transform-based sampling

Remaining distributions (Gamma, Poisson, StudentT, Beta, etc.) are more involved and can be discussed as follow-up.

**Comment by williambdean** [comment]
Whats the deal with the benchmark?

**Comment by williambdean** [comment]
Can you take look when you get the time @jessegrabowski :pray:

**Comment by jessegrabowski** [comment]
Yes and I recognize the hypocrisy of asking you to do it then not providing a review :)

re: benchmark, there's something about we already used 256 slots or something. @ricardoV94 knows what is wrong but can't be bothered to fix it.

**Comment by williambdean** [comment]
ha, all good 😄

**Comment by cetagostini** [comment]
Hey @williambdean 👋 — went through this and found a few things while testing the dispatches, so I pushed a commit on top (`515092d1`) addressing them. Hope you don't mind!

- **HalfNormal was wrong for nonzero `loc`**: it sampled `abs(loc + scale*z)`, but the support must be `[loc, ∞)`, i.e. `loc + scale*|z|` (verified against `scipy.stats.halfnorm`).
- **MvNormal**: batched params + an explicit `size` raised a reshape error, and an empty batch dim (`size=(0,)`) actually **segfaulted** the MLX compiled matmul. Replaced the two branches with a single broadcasting matmul `mean + (A @ z[..., None])[..., 0]` and guarded the empty case.
- **Integers**: bounds were cast to the output dtype *before* sampling, so e.g. `dtype="uint8"` collapsed `[250, 300)` to a single value. Now we sample at int64 width and cast the result (matches numpy's sample-then-cast).
- **Bernoulli/Categorical**: cast the bool/uint32 draw back to the declared int dtype.
- **Boilerplate**: folded Normal/Laplace/Gumbel into one loc-scale dispatch (`getattr(mx.random, op.name)`) + a `_shape_from_size` helper — this is the shape-boilerplate cleanup @ricardoV94 mentioned.
- Non-PCG64 generators now raise a clear `NotImplementedError` instead of an opaque `KeyError`.

Added regression tests for each. Branch merges cleanly with `main` (no conflicts). Did this with AI assistance (Cursor) — happy to tweak anything.

**Review by cetagostini — APPROVED** [review]
looks good to me!

**Comment by jessegrabowski** [comment]
did you just add a bunch of stuff and then approve your own code with a "lgtm" comment?

**Comment by williambdean** [comment]
The vibes look good

**Comment by jessegrabowski** [comment]
I'll give a review today, sorry for being slow

**Comment by cetagostini** [comment]
> did you just add a bunch of stuff and then approve your own code with a "lgtm" comment?

kinda 😅 I saw a few minor issues (only 2 files to adjust), and solve them, everything was almost there. But ofc, let's wait your reviews!

**Comment by williambdean** [comment]
What is needed to get this over the finish line?

File: tests/link/mlx/test_random.py [hunk 6]
```diff
@@ -0,0 +1,375 @@
...
+
+
+def test_gamma_not_implemented():
+    srng = RandomStream(seed=1)
+    rv = srng.gamma(shape=1.0, scale=1.0, size=(3,))
+    with pytest.raises(NotImplementedError, match="No MLX implementation"):
+        pytensor.function([], rv, mode="MLX", updates=srng.updates())
+
+
+def test_beta_not_implemented():
```
Comment (jessegrabowski) [inline tests/link/mlx/test_random.py:292]: These "not implemented" tests can be removed

File: tests/link/mlx/test_random.py [hunk 7]
```diff
@@ -0,0 +1,375 @@
...
+
+def test_laplace_shape_dtype():
+    check_shape_and_dtype(
+        lambda srng: srng.laplace(loc=0.0, scale=1.0, size=(7,)),
+        (7,),
+        "float32",
+    )
+
+
+def test_gumbel_shape_dtype():
```
Comment (jessegrabowski) [inline tests/link/mlx/test_random.py:159]: All of the `test_shape_dtype` tests could be collapsed to a single parameterized test, would be a bit easier to maintain in the long term

**Review by jessegrabowski — APPROVED** [review]
Looks good on my end, but I made some small suggestions on the tests. I say we put it in and see what happens. Highest risk for correctness is in `fgraph_convert`, I'd ask that you make sure that's carefully tested -- check that you're doing at least as much as the jax suite is doing.

File: pytensor/link/mlx/dispatch/random.py [hunk 8]
```diff
@@ -0,0 +1,248 @@
...
+    )
+
+
+@mlx_sample_fn.register(ptr.NormalRV)
+@mlx_sample_fn.register(ptr.LaplaceRV)
+@mlx_sample_fn.register(ptr.GumbelRV)
+def mlx_sample_fn_loc_scale(op, node):
+    """Loc-scale families: MLX names the standard sampler like the Op, so draw
+    it and apply ``loc + scale * z`` (mirrors the JAX dispatch)."""
+    mlx_op = getattr(mx.random, op.name)
```
Comment (jessegrabowski) [inline pytensor/link/mlx/dispatch/random.py]: Looking the MLX function up by `op.name` ties PyTensor's Op names to MLX's API surface. Works today, but a rename either side turns into an `AttributeError` here instead of the `NotImplementedError` the singledispatch fallback already gives you. An explicit `{ptr.NormalRV: mx.random.normal, ...}` is the same length and fails predictably.

File: pytensor/link/mlx/dispatch/random.py [hunk 9]
```diff
@@ -0,0 +1,248 @@
...
+        ).astype(convert_dtype_to_mlx(dtype))
+
+    return sample_fn
+
+
+@mlx_sample_fn.register(ptr.BernoulliRV)
+def mlx_sample_fn_bernoulli(op, node):
+    def sample_fn(rng_key, size, dtype, p):
+        p = mx.array(p)
+        shape = mlx_to_list_shape(size) if size is not None else None
```
Comment (jessegrabowski) [inline pytensor/link/mlx/dispatch/random.py:144]: Everything else goes through `_shape_from_size`, which broadcasts the parameters when `size` is None; bernoulli and categorical pass `None` and let MLX derive it from `p`. If that's deliberate a one-liner saying so would help — otherwise it reads as drift from the helper. Same on line 130.

File: pytensor/link/mlx/dispatch/random.py [hunk 10]
```diff
@@ -0,0 +1,248 @@
...
+        else:
+            batch_shape = mx.broadcast_shapes(mean.shape[:-1], cov.shape[:-2])
+
+        if 0 in tuple(batch_shape):
+            # Empty batch dim crashes MLX's compiled matmul; the draw is empty anyway.
+            return mx.broadcast_to(mean, [*batch_shape, n])
+
+        # Factor ``cov = A @ A.T`` so that ``mean + A @ z`` has covariance ``cov``.
+        if method == "cholesky":
+            A = mx.linalg.cholesky(cov, stream=mx.cpu)
```
Comment (jessegrabowski) [inline pytensor/link/mlx/dispatch/random.py:187]: Worth a word on why these three run on the CPU stream — I assume MLX's GPU linalg doesn't cover cholesky/svd/eigh, but the next reader has to guess.

File: pytensor/link/mlx/dispatch/random.py [hunk 11]
```diff
@@ -0,0 +1,248 @@
...
+
+
+@mlx_sample_fn.register(ptr.ExponentialRV)
+def mlx_sample_fn_exponential(op, node):
+    def sample_fn(rng_key, size, dtype, scale):
+        mlx_dtype = convert_dtype_to_mlx(dtype)
+        scale = mx.array(scale, dtype=mlx_dtype)
+        shape = _shape_from_size(size, scale)
+        u = mx.random.uniform(shape=shape, dtype=mlx_dtype, key=rng_key)
+        return -scale * mx.log(u)
```
Comment (jessegrabowski) [inline pytensor/link/mlx/dispatch/random.py]: `mx.random.uniform` is `[low, high)`, so `u = 0` gives `-inf` here and at the logistic on 233. I couldn't produce one in 200M draws — smallest `u` was 7.9e-9 — so this is insurance rather than a fix, but `-scale * mx.log1p(-u)` costs nothing.

**Review by jessegrabowski — COMMENTED** [review]
Rebased this onto main in a worktree — 12 commits, clean, no conflicts. With that on top it trains a convolutional VAE on MLX end to end (reparameterization trick and all), 30 epochs in 1.7s against numba's 23.8s for the same final loss. The `AttributeError: 'int' object has no attribute 'astype'` I hit before the rebase was version skew, not this PR.

Four small comments below, none blocking. Checked the MvNormal factorizations numerically — `A Aᵀ == cov` for all three methods.

**Comment by williambdean** [comment]
Thanks for the feedback, @jessegrabowski . Should be all addressed!

**Comment by jessegrabowski** [comment]
tests are failing :(

**Comment by jessegrabowski** [comment]
@williambdean i think some of these test failures aren't you and were solved by https://github.com/pymc-devs/pytensor/pull/2376 . A simple rebase will clear many/most/all.

**Comment by williambdean** [comment]
Rebase should be done!

**Comment by jessegrabowski** [comment]
🥳
